### ISSUE TITLE
Request for help for hask

### ISSUE THREAD

**Issue by DaddyGuitou** [miicam/MiiCam#24]
Hello,
I am having trouble applying the hack.
I followed the steps.
- Format in FAT32
- Modified older firmware
- Start the Chuangmi
- Copied the contents of SDCARD
- Start the Chuangmi
- Connection to the IP of the Chuangmi.

But connection refused, despite several tests.

Do not I realize something wrong?

The logs show some failed.

Thanks for your help.

**Comment by fliphess** [comment]
Hey @DaddyGuitou! Did you manage to get it working? 
Without much information, the issue you describe sounds like a configuration error with which the guys on discord can help you if you ask nicely :) 

I'm not working on the camera much at the moment due to busy with work and because of the summer...... If you need some help setting up the camera have a look at the [discord server](https://discord.gg/rjW2SSB) for some assistance setting up.
